#
# Herbert Yuan <yuanjp@hust.eud.cn>
# 2018/2/4
#

# this Makefile is included by the top Makefile.
# so all rules are available at main Makefile.
# don't use this file directly.

PROGRAMS :=
PROGRAMS_INSTALL :=
PROGRAMS_CLEAN :=

include $(USERSPACE_DIR)/busybox.mak
include $(USERSPACE_DIR)/openssl.mak
include $(USERSPACE_DIR)/iperf.mak
